#!/bin/bash
if [ $# -lt 1 -o $# -gt 2 ]; then
    OPTIONS=`ls ~/scripts/dictionaries/`
    echo -e "usage: $0\n$OPTIONS\n[keywords]"
    exit 0
fi

if [ $# -eq 1 ]; then
    cat ~/scripts/dictionaries/$1
    exit 0
fi

if [ $# -eq 2 ]; then
    grep $2 ~/scripts/dictionaries/$1 
fi

